version: "3.7"

services:
  luna-price-exporter:
    build: .
    environment:
      DENOMS: ukrw
    ports:
      - 8000:8000

  prometheus:
    image: prom/prometheus:v2.19.2
    command: --config.file=prometheus.yml
    volumes:
      - ./assets/prometheus.yml:/prometheus/prometheus.yml
    ports:
      - 9090:9090
