version: "3.7"

services:
  price-exporter:
    build: .

  prometheus:
    image: prom/prometheus:v2.19.2
    command: --config.file=prometheus.yml
    volumes:
      - ./assets/prometheus.yml:/prometheus/prometheus.yml
    ports:
      - 9090:9090
