version: "3.7"

services:
  exchange-price-exporter:
    build: .
    volumes:
      - ./config.toml:/app/config.toml
    ports:
      - 8000:8000

  prometheus:
    image: prom/prometheus:v2.19.2
    command: --config.file=prometheus.yml
    volumes:
      - ./assets/prometheus.yml:/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000

volumes:
  grafana:
