{
 "title": "Pairs data",
 "time": { "from": "2020-07-06T15:34:29.795Z", "to": "2020-07-06T15:50:39.750Z" },
 "templating": {
  "list": [
   { "name": "currency", "label": "Currency", "query": "label_values(candle, currency)" },
   { "name": "market", "label": "Market", "query": "label_values(candle, market)" }
  ]
 },
 "panels": [
  {
   "title": "Exchanges averages candles close price and volume",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(candle{olhcv=\"close\", currency=\"$currency\",market=\"$market\"})",
     "legendFormat": "average price"
    },
    {
     "expr": "avg(candle{olhcv=\"volume\", currency=\"$currency\",market=\"$market\"})",
     "legendFormat": "average volume"
    }
   ]
  },
  {
   "title": "Candles volumes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "candle{olhcv=\"volume\", currency=\"$currency\", market=\"$market\"}",
     "legendFormat": "{{ exchange }}"
    }
   ]
  },
  {
   "title": "Candles close price",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "candle{olhcv=\"close\", currency=\"$currency\",market=\"$market\"}",
     "legendFormat": "{{ exchange }}"
    }
   ]
  }
 ]
}