name: build

on:
  push:
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.7

    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
    - uses: actions/checkout@v2
    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Install dependencies
      run: |
        poetry install
    - name: Lint with flake8
      run: |
        poetry run flake8 . --count --show-source --statistics
    - name: Static typing with mypy
      run: |
        poetry run mypy --ignore-missing-imports --follow-imports=silent --show-column-numbers .
    - name: Test with pytest
      run: |
        poetry run pytest
    - id: version
      name: Output version
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        echo "::set-output name=version::v$(poetry version | cut -d" " -f2)"

  image:
    runs-on: ubuntu-latest
    needs: build

    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/checkout@v2
      - name: Build, tag, and push docker image to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: settenio/exchange-price-exporter
          tags: ${{needs.build.outputs.version}}
