name: CI

on:
  push:
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.7

    steps:
    - uses: actions/checkout@v2
    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Install dependencies
      run: |
        poetry install
    - name: Lint with flake8
      run: |
        poetry run flake8 . --count --show-source --statistics
    - name: Static typing with mypy
      run: |
        poetry run mypy --ignore-missing-imports --follow-imports=silent --show-column-numbers .
    - name: Test with pytest
      run: |
        poetry run pytest
